# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20, verbose_name='书籍名字')),
                ('bpub_date', models.DateField(verbose_name='发布日前')),
                ('bread', models.IntegerField(default=0, verbose_name='阅读量')),
                ('bcomment', models.IntegerField(default=0, verbose_name='评论量')),
                ('logo', models.ImageField(upload_to='img', verbose_name='封面')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '武侠小说',
                'verbose_name_plural': '武侠小说',
                'db_table': 'tb_books',
            },
        ),
    ]
