# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='logo',
        ),
    ]
