# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_remove_bookinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='logo',
            field=models.ImageField(null=True, upload_to='img', verbose_name='封面'),
        ),
    ]
